version: "3.8"

services:
  order-service:
    build:
      context: orderService
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "9090:9090"
    environment:
      SERVER_PORT: 9090
      SPRING_CLOUD_AZURE_STORAGE_QUEUE_ACCOUNT_NAME: azurestoragetest001
      SPRING_CLOUD_AZURE_STORAGE_QUEUE_ACCOUNT_KEY: ${AZURE_STORAGE_KEY}
      SPRING_CLOUD_AZURE_STORAGE_QUEUE_ENDPOINT: https://azurestoragetest001.queue.core.windows.net
      SPRING_CLOUD_AZURE_STORAGE_QUEUE_QUEUE_NAME: orders-queue

  payment-processor:
    build:
      context: paymentProcessor
      dockerfile: Dockerfile
    container_name: payment-processor
    ports:
      - "9091:9091"
    environment:
      SERVER_PORT: 9091
      SPRING_CLOUD_AZURE_STORAGE_QUEUE_ACCOUNT_NAME: azurestoragetest001
      SPRING_CLOUD_AZURE_STORAGE_QUEUE_ACCOUNT_KEY: ${AZURE_STORAGE_KEY}
      SPRING_CLOUD_AZURE_STORAGE_QUEUE_ENDPOINT: https://azurestoragetest001.queue.core.windows.net
      SPRING_CLOUD_AZURE_STORAGE_QUEUE_QUEUE_NAME: orders-queue

      SPRING_CLOUD_AZURE_STORAGE_BLOB_ACCOUNT_NAME: azurestoragetest001
      SPRING_CLOUD_AZURE_STORAGE_BLOB_ACCOUNT_KEY: ${AZURE_STORAGE_KEY}
      SPRING_CLOUD_AZURE_STORAGE_BLOB_ENDPOINT: https://azurestoragetest001.blob.core.windows.net
      SPRING_CLOUD_AZURE_STORAGE_BLOB_CONTAINER_NAME: audits

      SPRING_CLOUD_AZURE_COSMOS_ENDPOINT: https://azurecosmostest001.documents.azure.com:443/
      SPRING_CLOUD_AZURE_COSMOS_KEY: ${AZURE_COSMOS_KEY}
      SPRING_CLOUD_AZURE_COSMOS_DATABASE: OrdersDB
      SPRING_CLOUD_AZURE_COSMOS_CONNECTION_MODE: gateway