apiVersion: v1
kind: Service
metadata:
  name: payment-processor
spec:
  selector:
    app: payment-processor
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP
  