apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  SERVER_PORT: "9090"
  SPRING_CLOUD_AZURE_STORAGE_QUEUE_ACCOUNT_NAME: "azurestoragetest001"
  SPRING_CLOUD_AZURE_STORAGE_QUEUE_ACCOUNT_KEY: "REPLACE_WITH_ENV_VAR"
  SPRING_CLOUD_AZURE_STORAGE_QUEUE_ENDPOINT: "https://azurestoragetest001.queue.core.windows.net"
  SPRING_CLOUD_AZURE_STORAGE_QUEUE_QUEUE_NAME: "orders-queue"